### PR TITLE
session: Update UA key

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna/-/commit/3b1eaf56b9e8f840ccaf184635705dfad71b19f6

**Comment by joeshaw** [comment]
i was wondering why my automation wasn't working. thank you!

**Comment by stgraber** [comment]
@joeshaw well, even with that one in place, I'm still hitting an immediate `not Authorized` from their server, so there's something else that got broken...

**Comment by stgraber** [comment]
Oh, the API key in the dart repo is different too...

**Pull request merged**
